

import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://demo.broadengage.com/');
  await page.getByRole('textbox', { name: 'Email ID' }).click();
  await page.getByRole('textbox', { name: 'Email ID' }).fill('kshitij@iifetech.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Kshitij@123');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Kshitij@123');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.getByRole('button', { name: 'Data & Audience' }).click();
  await page.getByRole('button', { name: 'Datasets' }).click();
  await page.getByRole('button', { name: 'Create Data Set' }).click();
  await page.getByRole('tab', { name: 'CSV' }).click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Sample file to upload' }).click();
  const download = await downloadPromise;
  await page.locator('.MuiSvgIcon-root.MuiSvgIcon-fontSizeMedium.css-1ddcdg2 > path').click();
  await page.locator('body').setInputFiles('sample_dataset (2).csv');
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByText('Click to change file').click();
  await page.locator('body').setInputFiles('sample_dataset (1).csv');
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByText('SQL CSV').click();
  await page.getByRole('button', { name: 'Datasets' }).click();
  await page.getByRole('button', { name: 'Segments' }).click();
  await page.getByRole('button', { name: 'Suppression' }).click();
  await page.getByRole('button', { name: 'Create Suppression' }).click();
  await page.getByRole('button', { name: 'Create Suppression' }).click();
  await page.getByRole('row', { name: 'MA - 220 - Jan 22, 2026 14:58' }).getByRole('checkbox').check();
  await page.locator('div:nth-child(2) > .MuiSvgIcon-root').click();
  await page.locator('div').filter({ hasText: 'ID1MAAppendDelete' }).nth(1).click();
  await page.getByRole('button').click();
  await page.getByRole('button', { name: 'Datasets' }).click();
  await page.getByRole('button', { name: 'Segments' }).click();
  await page.getByRole('button', { name: 'Create Segment' }).click();
  await page.getByRole('textbox', { name: 'Enter segment name' }).click();
  await page.getByRole('textbox', { name: 'Enter segment name' }).fill('login');
  await page.getByRole('combobox').click();
  await page.locator('.MuiBackdrop-root.MuiBackdrop-invisible').click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('button', { name: 'Datasets' }).click();
  await page.getByRole('button', { name: 'Create Data Set' }).click();
  await page.getByRole('tab', { name: 'CSV' }).click();
  const download1Promise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Sample file to upload' }).click();
  const download1 = await download1Promise;
  await page.locator('div').filter({ hasText: /^Drag file here or browse for file upload$/ }).click();
  await page.locator('body').setInputFiles('sample_dataset (2).csv');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next', exact: true }).click();
  await page.getByRole('button', { name: 'Next', exact: true }).click();
  await page.getByRole('textbox', { name: 'Dataset Name' }).click();
  await page.getByRole('textbox', { name: 'Dataset Name' }).fill('Shivam');
  await page.getByRole('button', { name: 'Save Dataset' }).click();
  await page.getByRole('textbox', { name: 'Dataset Name' }).click();
  await page.getByRole('textbox', { name: 'Dataset Name' }).fill('Sh');
  await page.getByRole('button', { name: 'Save Dataset' }).click();
  await page.getByRole('button', { name: 'Save Dataset' }).click();
  await page.getByRole('textbox', { name: 'Dataset Name' }).fill('DATA');
  await page.getByRole('button', { name: 'Save Dataset' }).click();
  await page.getByRole('textbox', { name: 'Dataset Name' }).click();
  await page.getByRole('textbox', { name: 'Dataset Name' }).fill('DATA12');
  await page.getByRole('button', { name: 'Save Dataset' }).click();
  await page.getByRole('textbox', { name: 'Dataset Name' }).click();
  await page.getByRole('textbox', { name: 'Dataset Name' }).fill('Data');
  await page.getByRole('button', { name: 'Save Dataset' }).click();
  await page.getByRole('button', { name: 'Save Dataset' }).click();
  await page.getByRole('button', { name: 'Back' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('textbox', { name: 'Dataset Name' }).click();
  await page.getByRole('textbox', { name: 'Dataset Name' }).fill('ghe');
  await page.getByRole('button', { name: 'Save Dataset' }).click();
});