export const ROUTES = {
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",
  REGISTER_OTP: "/auth/registerOtp",
  RESET_PASSWORD: "/auth/resetpassword",
  ADD_NEW_PASSWORD: "/auth/addNewPassword",
  INVITE: "/invite",
  DASHBOARD: "/dashboard",
  // After login, shell can land on /dashboard or /journeys/active depending on env/config.
  DASHBOARD_ACTIVE_JOURNEYS: "/(dashboard|journeys/active)",
  JOURNEYS_ACTIVE: "/journeys/active",
  JOURNEYS_DRAFTS: "/journeys/drafts",
  JOURNEYS_CREATE: "/journeys/create",
  CAMPAIGNS_EMAIL: "/campaigns/email",
  CAMPAIGNS_SMS: "/campaigns/sms",
  AUDIENCE_SEGMENTS: "/audience/segments",
  AUDIENCE_SUPPRESSION: "/audience/suppression",
  DATA_CONNECT: "/data/connect-data",
  DATA_DATASETS: "/data/datasets",
  DATA_POOL: "/data-and-sources/pool",
  CHANNELS_EMAIL_TEMPLATES: "/channels/email/templates",
  CHANNELS_SMS_TEMPLATES: "/channels/sms/templates",
  CHANNELS_SMS_SSP: "/channels/sms/sspaccount",
  CHANNELS_EMAIL_CONNECTIONS: "/channels/email/connections",
  SETTINGS_USERS: "/settings/users",
  SETTINGS_SMS_TEMPLATE_FORM: "/settings/sms/template-form",
  SETTINGS_SMS_SSP_ACCOUNT: "/settings/sms/ssp-account",
  OFFER_FORM: "/offer-form",
  ASSETS_OFFERS: "/assets/offers",
} as const;
